apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: "Flux"
      organization: "influxdata"
      defaultBucket: "openclaw_metrics"
      tlsSkipVerify: true
    secureJsonData:
      token: "openclaw-token-12345"
    isDefault: true
    editable: true